### PR TITLE
Fix-nest-with-parameter

### LINKED ISSUE #213: Error when a nest with children nests has a parameter as an elasticity
# Replication of Issue

```julia
using MPSGE

M = MPSGEModel()

@parameter(M, sigma, 0)
@sector(M, X)
@commodity(M, C)

@production(M, X, [t=0, s=sigma, va=>s=1], begin
    @output(C, 1, t)
    @input(C, 1, s)
    @input(C, 1, va)
end)
```

# Description of Issue

We build cost function recursively. When a parent nest, `s`, has a parameter as an elasticity, `sigma`, and has a child nest, `va`, the virtual cost functions are not being generated correctly. 

# Solution

Add this logic

### PR DESCRIPTION
**Pull request by mitchphillipson**
Closes #213

### CODE REVIEW

File: src/macros/@production.jl [hunk 1]
```diff
@@ -57,10 +57,10 @@ function build_cost_function(N::Node; virtual = :full)
 
     # If the cost function exists, return it
     if !isnothing(N.cost_function_virtual)
-        return cost_function(N, virtual = :virtual)
+        return MPSGE.cost_function(N, virtual = :virtual)
     end
 
-    cost_function = MPSGE.cost_function(N; virtual = :partial, cf = build_cost_function)
+    cost_function = MPSGE.cost_function(N; virtual = :partial, cf = MPSGE.build_cost_function)
```
Comment (mitchphillipson) [inline src/macros/@production.jl:63]: This gets called in a `@expression` macro. We need the explicit reference to MPSGE otherwise it looks in the local scope for `build_cost_function`

**Review by EliLazarus — APPROVED** [review]
Beaut!
